### ISSUE TITLE
Fix 'Unnecessary &quot;else&quot; after &quot;return&quot;' issue in helpers.py

### ISSUE THREAD

**Issue by jwbn** [wbnk/youtube-dl-helper#17]
[CodeFactor](https://www.codefactor.io/repository/github/wbnk/youtube-dl-helper) found an issue: Unnecessary &quot;else&quot; after &quot;return&quot;

It's currently on:
[helpers.py:10
](https://www.codefactor.io/repository/github/wbnk/youtube-dl-helper/source/master/helpers.py#L10)Commit 8fcff5054691bce7f5160e4b2a46e8faeea4a2b1

**Comment by jack961** [comment]
fixed
